name: Java CI with Maven and Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update db url
        run: sed -i 's/${DB_URL}/${{ secrets.DB_URL }}/' src/main/resources/application.properties

      - name: Update db username
        run: sed -i 's/${DB_USERNAME}/${{ secrets.DB_USERNAME }}/' src/main/resources/application.properties

      - name: Update db password
        run: sed -i 's/${DB_PASSWORD}/${{ secrets.DB_PASSWORD }}/' src/main/resources/application.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven and Run Tests
        run: mvn clean verify --batch-mode --file pom.xml

      - name: Upload Code Coverage Report
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/site/jacoco/index.html

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Execute update.sh on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /srv/Server-Monitoring-Tool  &&
            sudo ./update2.sh
